### ISSUE TITLE
I want to add  Solution of SQL Problems on   Hackerrank  

### ISSUE THREAD

**Issue by Harshal0506** [rohitsinghkcodes/Hacktober-CP-contributions#14]
I have started learning SQL I need A month Time to Learn it and solve the problem .
I will make sure the folder will be properly managed and will be user friendly

If you wish to assign me with SQL of Hackerrank I will Make sure I will do my best 
Hoping for a +ve response from your side
cheers
@rohitsinghkcodes

**Comment by rohitsinghkcodes** [comment]
Yeah full support from my side brother. Keep it  up.
@Harshal0506
